coordinatorHost: 127.0.0.1 # MACHINE_IP
coordinatorPort: 4000
localWorkerHost: 127.0.0.1 # MACHINE_IP
workerId: 3
logLevel: LOG_WARNING

physicalSources:
  - logicalSourceName: gps_position
    physicalSourceName: follower
    type: MQTT_SOURCE
    configuration:
      url: ws://127.0.0.1:9001 # MACHINE_IP:9001
      topic: follower_gps_fix
