coordinatorHost: 127.0.0.1 # MACHINE_IP
coordinatorPort: 4000
localWorkerHost: 127.0.0.1 # MACHINE_IP
workerId: 4
logLevel: LOG_WARNING

physicalSources:
  - logicalSourceName: gps_position
    physicalSourceName: leader_inv
    type: MQTT_SOURCE
    configuration:
      url: ws://127.0.0.1:9001 # MACHINE_IP:9001
      topic: leader_inv_gps_fix
