coordinatorHost: 192.168.0.188 # MACHINE_IP
coordinatorPort: 4000
localWorkerHost: 192.168.0.188 # MACHINE_IP
workerId: 2
logLevel: LOG_WARNING

physicalSources:
  - logicalSourceName: gps_position
    physicalSourceName: leader
    type: MQTT_SOURCE
    configuration:
      url: ws://192.168.0.188:9001 # MACHINE_IP:9001
      topic: leader_gps_fix
