coordinatorHost: 0.0.0.0
coordinatorPort: 4000
localWorkerHost: 0.0.0.0
workerId: 4
logLevel: LOG_WARNING

physicalSources:
  - logicalSourceName: soil_humidity
    physicalSourceName: sensors
    type: MQTT_SOURCE
    configuration:
      url: ws://127.0.0.1:9001
      topic: humidity_producer
