services:
  nebula-api:
    build:
      context: ../../..
      dockerfile: deployments/nebulastream/api/config/Dockerfile.api
    network_mode: host
    volumes:
      - ../../../app:/code/app
      - ./jar_query:/jars
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${API_PORT}", "--reload" ]
    env_file: .env
